services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080

      # RabbitMQ
      RabbitMq__Host: rabbitmq
      RabbitMq__VirtualHost: /
      RabbitMq__Username: guest
      RabbitMq__Password: guest

      # SQLite (SEM mudar código)
      ConnectionStrings__Default: "Data Source=/data/users.db"

      # JWT
      Jwt__Secret: "super_secret_key_change_me_please_32_chars_min"
      Jwt__Issuer: "users-api"
      Jwt__Audience: "fcg-fase2"
    volumes:
      - users_data:/data
    ports:
      - "5001:8080"
    restart: unless-stopped

  catalog-api:
    build:
      context: ./catalog-api
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080

      # RabbitMQ
      RabbitMq__Host: rabbitmq
      RabbitMq__VirtualHost: /
      RabbitMq__Username: guest
      RabbitMq__Password: guest

      # SQLite (SEM mudar código)
      ConnectionStrings__Default: "Data Source=/data/catalog.db"
    volumes:
      - catalog_data:/data
    ports:
      - "5003:8080"
    restart: unless-stopped

  payments-api:
    build:
      context: ./payments-api
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080

      # RabbitMQ
      RabbitMq__Host: rabbitmq
      RabbitMq__VirtualHost: /
      RabbitMq__Username: guest
      RabbitMq__Password: guest
    ports:
      - "5004:8080"
    restart: unless-stopped

  notifications-api:
    build:
      context: ./notifications-api
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080

      # RabbitMQ
      RabbitMq__Host: rabbitmq
      RabbitMq__VirtualHost: /
      RabbitMq__Username: guest
      RabbitMq__Password: guest
    ports:
      - "5002:8080"
    restart: unless-stopped

volumes:
  users_data:
  catalog_data:
