apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
        - name: payments-api
          image: fcg-fase2-payments-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: fcg-fase2-config
                  key: ASPNETCORE_ENVIRONMENT

            # RabbitMQ
            - name: RabbitMq__Host
              valueFrom:
                configMapKeyRef:
                  name: fcg-fase2-config
                  key: RABBITMQ_HOST
            - name: RabbitMq__VirtualHost
              valueFrom:
                configMapKeyRef:
                  name: fcg-fase2-config
                  key: RABBITMQ_VHOST
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: fcg-fase2-secrets
                  key: RABBITMQ_USERNAME
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: fcg-fase2-secrets
                  key: RABBITMQ_PASSWORD

            # Filas
            - name: Queues__OrderPlaced
              valueFrom:
                configMapKeyRef:
                  name: fcg-fase2-config
                  key: QUEUE_ORDER_PLACED
            - name: Queues__PaymentProcessed
              valueFrom:
                configMapKeyRef:
                  name: fcg-fase2-config
                  key: QUEUE_PAYMENT_PROCESSED_CATALOG
---
apiVersion: v1
kind: Service
metadata:
  name: payments-api
spec:
  selector:
    app: payments-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
