apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: fcg-fase2-users-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: fcg-fase2-config
                  key: ASPNETCORE_ENVIRONMENT

            # SQLite (secret por requisito)
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: fcg-fase2-secrets
                  key: USERS_DB

            # RabbitMQ
            - name: RabbitMq__Host
              valueFrom:
                configMapKeyRef:
                  name: fcg-fase2-config
                  key: RABBITMQ_HOST
            - name: RabbitMq__VirtualHost
              valueFrom:
                configMapKeyRef:
                  name: fcg-fase2-config
                  key: RABBITMQ_VHOST
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: fcg-fase2-secrets
                  key: RABBITMQ_USERNAME
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: fcg-fase2-secrets
                  key: RABBITMQ_PASSWORD

            # JWT
            - name: Jwt__Secret
              valueFrom:
                secretKeyRef:
                  name: fcg-fase2-secrets
                  key: JWT_SECRET
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: fcg-fase2-secrets
                  key: JWT_ISSUER
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: fcg-fase2-secrets
                  key: JWT_AUDIENCE
          volumeMounts:
            - name: users-data
              mountPath: /data
      volumes:
        - name: users-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
spec:
  selector:
    app: users-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
